name: sea-iss-submission
channels:
  - conda-forge
dependencies:
  - python=3.12
  - jupyter-book
  - jupyterlab
  - jupyterlab-myst
  - sphinx-pythia-theme==2022.3.29
  - sphinxcontrib-bibtex
  - docutils
  - lxml-html-clean
