name: JupyterBook
#name: Build and Publish JupyterBook to GitHub Pages

on:
  [push]
  
permissions:
  contents: read
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.7 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jupyter-book
        pip install sphinx-pythia-theme
        pip install -r requirements.txt
        PATH="${PATH}:${HOME}/.local/bin"
   # - name: Build book TOC file 
   #   run: |
   #     #jupyter-book toc .
    - name: Push _build/html to gh-pages
      run: |
        sudo chown -R $(whoami):$(whoami) .
        git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
