name: JupyterBook
#name: Build and Publish JupyterBook to GitHub Pages

on:
  [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.10 
    - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          python-version: "3.10"  # binderbot is failing with python 3.11
          activate-environment: environment.yml
          use-mamba: true

    - name: Install Python dependencies
      run: |
        mamba install -c conda-forge jupyter-book pip
        pip install sphinx-pythia-theme
        pip install git+https://github.com/pangeo-gallery/binderbot.git
        mamba env update -n sea-iss-template -f environment.yml

        #pip install git+git://github.com/executablebookproject/cli.git#egg=master
        pip install ghp-import
        PATH="${PATH}:${HOME}/.local/bin"
   # - name: Build book TOC file 
   #   run: |
   #     #jupyter-book toc .
    - name: Build book HTML 
      run: |
        jupyter-book build .
    - name: Push _build/html to gh-pages
      run: |
        sudo chown -R $(whoami):$(whoami) .
        git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git config --global user.name "$GITHUB_ACTOR"
        git remote set-url origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY"
        ls -lrt
        ghp-import _build/html -f -p -n
